sudo: false
cache: pip
jdk: openjdk8
python: 3.7

install:
  - pip install .
  - pip install pyspark
  - pip install coverage

script:
  - SPARK_HOME=$(python -c "import os; import pyspark; print(os.path.dirname(pyspark.__file__))") pytest
