dist: bionic
language: python
cache: pip
python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt install openjdk-8-jdk-headless
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64

install:
  - pip install .
  - pip install pyspark
  - pip install coverage

script:
  - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 SPARK_HOME=$(python -c "import os; import pyspark; print(os.path.dirname(pyspark.__file__))") pytest
