sudo: false
dist: xenial
language: python
cache: pip
python:
  - "3.7"
  - "pypy3"

install:
  - pip install .
  - pip install pyspark
  - pip install coverage

script: SPARK_HOME=$(python -c "import os; import pyspark; print(os.path.dirname(pyspark.__file__))") pytest
